name: Deploy prod
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      - name: Deploy
        run: netlify deploy --prod --dir=. --site=$NETLIFY_SITE_ID
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PAT }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PROJECT_ID }}